name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: avipa
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd /var/www/gloup/backend/Gloup-Test-Backend

            echo "Pulling latest code..."
            git pull origin main

            echo "Stopping containers..."
            docker compose down

            echo "Building containers..."
            docker compose build --no-cache

            echo "Starting containers..."
            docker compose up -d

            echo "Deployment completed"

            docker ps